const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const {open}=require('./explore.js'); const {execFileSync}=require('child_process');
const Q=q=>execFileSync('psql',['-h','/tmp','-p','5433','-U','postgres','-d','gtapp','-Atc',q]).toString().trim();
const W=(p,ms)=>p.waitForTimeout(ms); const cell=n=>`.screen.active .num-cell[data-idx="${n-1}"]`;
const notice=p=>p.evaluate(()=>{ const n=[...document.querySelectorAll('div')].filter(d=>d.offsetParent && /#\d+ — /.test(d.textContent) && d.children.length===0).map(d=>d.textContent); return n.slice(-1)[0]||''; });
(async()=>{ const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
 let x=await open(b,'esophagus'), p=x.p; p.on('pageerror',e=>console.log('ERR',e.message));
 await p.click(cell(1)); await W(p,900);
 console.log('eso: tap #1 (ruled at outer) → windows:', await p.evaluate(()=>[...document.querySelectorAll('.overlay.open')].map(o=>o.id).join(',')||'none'), '| message:', (await notice(p)).slice(0,80));
 await p.click(cell(3)); await W(p,900);
 console.log('eso: tap #3 (eso ok, legs next) → window:', await p.evaluate(()=>[...document.querySelectorAll('.overlay.open')].map(o=>o.id).join(',')), '| USDA button shown:', await p.evaluate(()=>getComputedStyle(document.querySelector('#esoWarnModal .gt-usda-chg')).display));
 await p.evaluate(()=>document.querySelectorAll('.overlay.open').forEach(o=>o.classList.remove('open')));
 await p.evaluate(()=>{ gtUsdaStart('eso'); document.getElementById('gtHoldNum').value='3'; }); await W(p,300); await p.click('#gtUsdaOk'); await W(p,1500);
 console.log('eso: USDA typed #3 → message:', (await notice(p)).slice(0,90), '| server holds:', Q("select count(*) from animal_holds where resolved_at is null"));
 await p.evaluate(()=>{ gtUsdaStart('eso'); document.getElementById('gtHoldNum').value='2'; }); await W(p,300); await p.click('#gtUsdaOk'); await W(p,2000);
 console.log('eso: USDA #2 (its area) → server:', Q("select string_agg((animal_id+1)||':'||station,',') from animal_holds where resolved_at is null"));
 await x.ctx.close();
 x=await open(b,'outer'); p=x.p; await W(p,1000);
 console.log('outer top bar:', JSON.stringify(await p.evaluate(()=>document.querySelector('#scOuter .gt-tb').innerText)));
 await x.ctx.close();
 x=await open(b,'legs'); p=x.p; await W(p,1000);
 await p.evaluate(()=>{ gtUsdaStart('legs'); document.getElementById('gtHoldNum').value='3'; }); await W(p,300); await p.click('#gtUsdaOk'); await W(p,2000);
 console.log('legs: USDA #3 (its area) → server:', Q("select string_agg((animal_id+1)||':'||station,',' order by id) from animal_holds where resolved_at is null"));
 await x.ctx.close(); await b.close(); })();
