const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const {open}=require('./explore.js'); const {execFileSync}=require('child_process');
const Q=q=>execFileSync('psql',['-h','/tmp','-p','5433','-U','postgres','-d','gtapp','-Atc',q]).toString().trim();
const W=(p,ms)=>p.waitForTimeout(ms); const cell=n=>`.screen.active .num-cell[data-idx="${n-1}"]`;
const notice=p=>p.evaluate(()=>{ const n=[...document.querySelectorAll('div')].filter(d=>d.offsetParent && /#\d+ — /.test(d.textContent) && d.children.length===0).map(d=>d.textContent); return n.slice(-1)[0]||''; });
const holds=()=>Q("select coalesce(string_agg((animal_id+1)||':'||station,',' order by id),'-') from animal_holds where resolved_at is null");
const usda=async(p,st,n)=>{ await p.evaluate(([st,n])=>{ gtUsdaStart(st); document.getElementById('gtHoldNum').value=String(n); },[st,n]); await W(p,300); await p.click('#gtUsdaOk'); await W(p,2000); };
(async()=>{ const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
 let x=await open(b,'slaughter'), p=x.p;
 await p.click(cell(3)); await W(p,900);
 console.log('slaughter: tap #3 (esophagus checked it) →', await p.evaluate(()=>[...document.querySelectorAll('.overlay.open')].map(o=>o.id).join(',')||'no window'), '|', (await notice(p)).slice(0,70));
 await p.click(cell(2)); await W(p,900);
 console.log('slaughter: tap #2 (nobody after it yet) →', await p.evaluate(()=>[...document.querySelectorAll('.overlay.open')].map(o=>o.id).join(',')||'no window'));
 await x.ctx.close();
 x=await open(b,'esophagus'); p=x.p;
 await p.click(cell(4)); await W(p,900);
 console.log('eso: tap #4 (legs printed) →', await p.evaluate(()=>[...document.querySelectorAll('.overlay.open')].map(o=>o.id).join(',')||'no window'), '|', (await notice(p)).slice(0,70));
 await p.click(cell(3)); await W(p,900);
 console.log('eso: tap #3 (only checked here) → window', await p.evaluate(()=>[...document.querySelectorAll('.overlay.open')].map(o=>o.id).join(',')), '| USDA button:', await p.evaluate(()=>getComputedStyle(document.querySelector('#esoWarnModal .gt-usda-chg')).display));
 await p.evaluate(()=>document.querySelectorAll('.overlay.open').forEach(o=>o.classList.remove('open')));
 await usda(p,'eso',3); console.log('eso: USDA #3 →', holds());
 await usda(p,'eso',4); console.log('eso: USDA #4 (legs printed) →', (await notice(p)).slice(0,80), '| holds', holds());
 await x.ctx.close();
 x=await open(b,'legs'); p=x.p;
 await usda(p,'legs',4); console.log('legs: USDA #4 →', holds());
 await x.ctx.close(); await b.close(); })();
