#!/bin/bash
# Writes /etc/keepalived/keepalived.conf from gt-plant.conf (run on each server, as root).
. "$(dirname "$0")/../gt-lib.sh"
gt_check_secrets
pri=$([ "$GT_SELF" = "A" ] && echo 150 || echo 100)
out="${1:-/etc/keepalived/keepalived.conf}"
cat > "$out" <<CONF
# generated by make-keepalived.sh for server $GT_SELF — do not edit, edit gt-plant.conf and run again
global_defs { enable_script_security; script_user root }
vrrp_script chk_main { script "$(cd "$(dirname "$0")" && pwd)/check_pg.sh"; interval 2; fall 2; rise 2 }
vrrp_instance GT_VIP {
  state BACKUP
  nopreempt
  interface $GT_IFACE
  virtual_router_id 51
  priority $pri
  advert_int 1
  unicast_src_ip $GT_SELF_IP
  unicast_peer { $GT_PEER_IP }
  authentication { auth_type PASS; auth_pass ${GT_VRRP_PASS:0:8} }
  virtual_ipaddress { $GT_VIP/24 }
  track_script { chk_main }       # only the MAIN server (not in recovery) holds the address
}
CONF
chmod 600 "$out"
gt_log "keepalived settings written to $out (server $GT_SELF, priority $pri)"
