// Every caption of the video, in Hebrew and English (the English is also the narration).
module.exports = {
  i1: ['מסך ריק. פותחים את תוכנת GlattTrack בטאבלט של ראש הצוות', 'An empty screen. We open the GlattTrack app on the team leader\'s tablet.'],
  i2: ['התוכנה מתחברת לשרת המפעל. בשרת עוד אין ראש צוות — זו התקנה ראשונה', 'The app connects to the plant server. The server has no team leader yet, so this is the first installation.'],
  i3: ['לוחצים "יצירת ראש הצוות הראשון"', 'Tap: create the first team leader.'],
  i4: ['ממלאים: שם ראש הצוות, קוד אישי, וקוד ההתקנה של השרת (מהמתקין)', 'Fill in the team leader\'s name, a personal code, and the server setup code from the installer.'],
  i5: ['השרת בודק את קוד ההתקנה ומאשר את ההתקנה', 'The server checks the setup code and approves the installation.'],
  i6: ['הטאבלט הזה נרשם כמכשיר של ראש הצוות. נפתח עמוד ההתקנה — פעם אחת בלבד', 'This tablet is now registered as the team leader\'s device. The setup page opens, only this once.'],
  i7: ['קוד שחזור — אפשר לדלג ולעשות אחר כך', 'A recovery code. It can be skipped and made later.'],
  i8: ['בחירת המסכים שעובדים במפעל: שחיטה, וושט, רגליים וראש, פנים, חוץ, חלקים, חותמות. ושומרים', 'Choose the screens the plant uses: slaughter, esophagus, legs and head, inner, outer, small parts, and stamps. Then save.'],
  i9: ['עובדים, צימוד טאבלטים, בעלים ומדפסות — עכשיו או אחר כך', 'Workers, pairing the tablets, the owner and the printers can be done now or later.'],
  i10: ['מסך ראש הצוות פתוח. מכאן — יום עבודה, תחנה אחרי תחנה', 'The team leader screen is open. Now, a working day, station by station.'],

  s1: ['טאבלט השחיטה. השוחט לוחץ כפתור אחד לכל בהמה, והמספר הבא מתמלא לבד', 'The slaughter tablet. The shochet presses one button per animal, and the next number fills in by itself.'],
  s2: ['בהמה 5 — נבלה', 'Animal five: nevela.'],
  s3: ['לחיצה על מספר שכבר סומן פותחת תיקון — רק לפני שהשלב הבא נגע בו', 'Tapping a marked number opens a correction, only before the next station has touched it.'],
  e1: ['טאבלט בדיקת הוושט', 'The esophagus check tablet.'],
  e2: ['ניסיון לדלג לבהמה 3 — המערכת לא מאפשרת', 'Trying to skip to animal three. The system does not allow it.'],
  e3: ['לוחצים על הבהמה המהבהבת ובוחרים "תקין"', 'Tap the blinking animal and choose OK.'],
  l1: ['טאבלט רגליים וראש. המדבקות מודפסות מיד אחרי השחיטה — לפני הפסיקה', 'The legs and head tablet. Stickers are printed right after slaughter, before the ruling.'],
  l2: ['לחיצה ראשונה מדפיסה מדבקות רגליים', 'The first tap prints the leg stickers.'],
  l3: ['לחיצה שנייה מדפיסה את מדבקת הראש', 'The second tap prints the head sticker.'],
  l4: ['כך כל בהמה, לפי הסדר — גם נבלה מקבלת מדבקת מספר', 'Every animal in order. A nevela also gets a number sticker.'],
  l5: ['מדבקה של נבלה: כתוב עליה נבלה, בעברית ובאנגלית', 'A nevela sticker says nevela, in Hebrew and in English.'],
  in1: ['טאבלט בודק הפנים. לוחצים על הבהמה הבאה בתור', 'The inner inspector\'s tablet. Tap the next animal in line.'],
  in2: ['בדיקת כרס: כשר', 'Rumen check: kosher.'],
  in3: ['בית הכוסות: כשר', 'Maw: kosher.'],
  in4: ['ציור הריאה: מסמנים באצבע', 'The lung drawing: mark it with a finger.'],
  in5: ['"אישור לבודק חוץ" — הבהמה עוברת לחוץ יחד עם הציור', 'Approve for the outer inspector. The animal moves on with its drawing.'],
  in6: ['בהמה 3 — טרף: לחיצה ראשונה שואלת, השנייה פוסקת', 'Animal three is treif. The first tap asks, the second tap rules.'],
  in7: ['בהמות 2, 4 ו-6 — כשר ואישור', 'Animals two, four and six: kosher, and approve.'],
  o1: ['טאבלט בודק החוץ. רואים את ציור הריאה, ופוסקים', 'The outer inspector\'s tablet. The lung drawing is shown, and the inspector rules.'],
  o2: ['בהמה 1 — גלאט', 'Animal one: Glatt.'],
  o3: ['בהמה 2 — בית יוסף, בהמה 4 — גלאט, בהמה 6 — כשר', 'Animal two: Beit Yosef. Animal four: Glatt. Animal six: kosher.'],
  o4: ['הפסיקה נקבעה. חוזרים לטאבלט הרגליים — למיון', 'The ruling is made. Back to the legs tablet, for sorting.'],
  ls1: ['מיון רגליים: סורקים את המדבקה שהודפסה לפני הפסיקה', 'Leg sorting: scan the sticker that was printed before the ruling.'],
  ls2: ['המספר מתעדכן: המסך מראה את הפסיקה העדכנית מהשרת', 'The number is updated: the screen shows the current ruling from the server.'],
  ls3: ['רגל 3 — טרף, באדום', 'Leg three: treif, in red.'],
  p1: ['טאבלט חלקים קטנים — לחיים ולשון', 'The small parts tablet: cheeks and tongue.'],
  p2: ['בהמה 3 טרף — המסך מסרב להדפיס', 'Animal three is treif. The screen refuses to print.'],
  p3: ['בהמה 1 — לחיצה אחת מדפיסה 3 מדבקות: לחי 1, לחי 2, לשון', 'Animal one: one tap prints three stickers: cheek one, cheek two, and tongue.'],
  p4: ['בהמה 2 — בית יוסף', 'Animal two: Beit Yosef.'],
  st1: ['טאבלט חותמות ושקילה — החלק הגדול של הבהמה', 'The stamps and weighing tablet, for the main carcass.'],
  st2: ['סורקים את מדבקת הבהמה — יוצאות 5 חותמות לפי הפסיקה', 'Scan the animal\'s sticker. Five stamps print, by the ruling.'],
  st3: ['שקילה: סורקים מדבקת משקל — צד ימין ואז צד שמאל', 'Weighing: scan the weight label, right side and then left side.'],
  st4: ['בהמה 1 הוחתמה ונשקלה. ממשיכים לבאה', 'Animal one is stamped and weighed. On to the next.'],
  t1: ['בחזרה אצל ראש הצוות: כרטיס בהמה 1 — כל ההיסטוריה', 'Back with the team leader: the card of animal one, with its whole history.'],
  t2: ['כל פעולה: מי, מתי, ומאיזה טאבלט', 'Every action: who, when, and from which tablet.'],
  t3: ['דוגמאות מדבקות — כל הסוגים', 'Sample stickers, every kind.'],
  t4: ['למעלה: רגליים וראש, לפני הפסיקה. למטה: חלקים וחותמות, אחרי הפסיקה', 'Top row: legs and head, before the ruling. Bottom row: parts and stamps, after the ruling.'],
  // the sticker windows
  k_legs: ['מדבקת רגליים. בחוץ: מספר, תאריך עברי ולועזי, שעה. ב-QR: כל הפרטים', 'The legs sticker. Printed: the number, the Hebrew and Gregorian dates, and the time. In the QR code: everything.'],
  k_head: ['מדבקת ראש — אותם פרטים', 'The head sticker has the same details.'],
  k_nev: ['מדבקת נבלה', 'The nevela sticker.'],
  k_parts1: ['מדבקת חלקים: הפסיקה בעברית ובאנגלית — גלאט / Glatt', 'The parts sticker: the ruling in Hebrew and English, Glatt.'],
  k_parts2: ['בית יוסף / Beit Yosef', 'Beit Yosef.'],
  k_stamp: ['החותמת של בהמה 1 — לפי הפסיקה', 'The stamp of animal one, by its ruling.'],
};
