const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const fs=require('fs');
const APP='/home/user/empower-design-studio/glatttrack/kosher-app-v10.32.html';
(async()=>{ const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
 const ctx=await b.newContext({viewport:{width:900,height:1300}});
 await ctx.route(u=>new URL(u).pathname==='/', r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:fs.readFileSync(APP)}));
 await ctx.addInitScript(()=>{ window._gtLicShown=true; if(localStorage.getItem('i'))return; localStorage.setItem('ks_lang_by_screen',JSON.stringify({scManager:'he',scNav:'he'})); localStorage.setItem('i','1'); });
 const p=await ctx.newPage(); p.on('pageerror',e=>console.log('ERR',e.message)); await p.goto('http://localhost:8083/'); await p.waitForTimeout(6000);
 await p.evaluate(()=>{ document.querySelectorAll('.overlay.open').forEach(o=>o.classList.remove('open')); mgrEnter(); }); await p.waitForTimeout(1000);
 await p.fill('#loginCodeInput','e2e-tl-code-7731'); await p.evaluate(()=>[...document.querySelectorAll('#loginModal button')].pop().click());
 await p.waitForTimeout(6000); await p.evaluate(()=>{ document.querySelectorAll('.overlay.open').forEach(o=>o.classList.remove('open')); try{gtWizardClose(true);}catch(e){} mgrTab('monitor'); });
 await p.waitForTimeout(4000);
 const vis=()=>p.evaluate(()=>['ov','tr','sys'].map(k=>{const b=document.getElementById('gtToday_'+k);return k+'['+(b&&b.style.display!=='none'?'shown':'hidden')+']: '+(b?[...b.children].filter(e=>e.style.display!=='none').map(e=>e.id||e.getAttribute('data-t')||e.className).join(','):'-');}).join('  |  '));
 console.log('bar:', await p.evaluate(()=>document.getElementById('gtTodayBar').innerText.replace(/\n/g,' ')));
 console.log(await vis());
 await p.screenshot({path:__dirname+'/shots/today-ov.png'});
 await p.evaluate(()=>gtTodaySub('tr')); await p.waitForTimeout(800); await p.screenshot({path:__dirname+'/shots/today-tr.png'});
 await p.evaluate(()=>gtTodaySub('sys')); await p.waitForTimeout(800); console.log(await vis()); await p.screenshot({path:__dirname+'/shots/today-sys.png'});
 await p.evaluate(()=>gtTodaySub('ov')); await p.evaluate(()=>gtOpenHealth()); await p.waitForTimeout(800);
 console.log('health banner → sub-tab:', await p.evaluate(()=>_gtTodaySub));
 await b.close(); })();
