const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const {open}=require('./explore.js');
const {execSync}=require('child_process'); const q=s=>execSync(`psql -h /tmp -p 5433 -U postgres -d gtapp -At`,{input:s}).toString().trim();
const W=(p,ms)=>p.waitForTimeout(ms);
const cells=(p,n)=>p.evaluate(n=>[...Array(n).keys()].map(i=>{const c=document.querySelector(`.screen.active .num-cell[data-idx="${i}"]`);return (i+1)+':'+(c.innerText.replace(/\s+/g,' ').replace(/^\d+ ?/,'')||'—')+(c.className.includes('next')?'*':'');}).join(' | '),n);
(async()=>{ const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
 const L=await open(b,'legs'); await W(L.p,2000);
 console.log('split:', await L.p.evaluate(()=>_lgSplit()), '| role:', await L.p.evaluate(()=>_lgRole()), '| title:', await L.p.evaluate(()=>document.getElementById('lgRoleLbl').textContent));
 console.log('LEGS before :', await cells(L.p,4));
 await L.p.evaluate(()=>{ lgInstance=1; _lgTitle(); lgRenderGrid(); });
 console.log('HEAD before :', await cells(L.p,4), '| title:', await L.p.evaluate(()=>document.getElementById('lgRoleLbl').textContent));
 await L.p.evaluate(()=>{ lgInstance=0; lgRenderGrid(); lgTap(0); }); await W(L.p,2500);
 console.log('server #1 after legs tap:', q("select legs_stickers||'/'||head_stickers from animals_pilot where id=0"));
 await L.p.evaluate(()=>{ lgInstance=1; lgRenderGrid(); });
 console.log('HEAD after legs:', await cells(L.p,4));
 await L.p.evaluate(()=>{ lgTap(0); }); await W(L.p,2500);
 console.log('server #1 after head tap:', q("select legs_stickers||'/'||head_stickers from animals_pilot where id=0"));
 await L.ctx.close();
 const I=await open(b,'inner'); await W(I.p,2500);
 console.log('INNER       :', await cells(I.p,4));
 await I.ctx.close(); await b.close(); })();
