const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const {open}=require('./explore.js'); const {execSync}=require('child_process');
const Q=q=>execSync(`psql -h /tmp -p 5433 -U postgres -d gtapp -Atc "${q}"`).toString().trim();
const W=(p,ms)=>p.waitForTimeout(ms); const cell=n=>`.screen.active .num-cell[data-idx="${n-1}"]`;
const cls=(p,n)=>p.evaluate(n=>{const c=document.querySelector(`.screen.active .num-cell[data-idx="${n-1}"]`);return c?c.className+' | '+c.innerText.replace(/\n/g,' '):'-';},n);
(async()=>{ const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
 let x=await open(b,'slaughter'); let p=x.p; for(let i=0;i<4;i++){await p.click('#tSlBtnS');await W(p,900);} await W(p,1500); await x.ctx.close();
 x=await open(b,'esophagus'); p=x.p; p.on('pageerror',e=>console.log('ERR',e.message));
 await p.click('#scEsophagus .gt-tbq'); await W(p,600); console.log('eso ? default number:', await p.inputValue('#gtHoldNum'));
 await p.click('#gtSheet button:has-text("סמן")'); await W(p,2500);
 console.log('eso cells 1,2:', await cls(p,1),' || ',await cls(p,2));
 await p.click(cell(2)); await W(p,700); await p.click(`[onclick="esoDecide('ok')"]`); await W(p,1200);
 await p.click(cell(1)); await W(p,700); console.log('eso modal on ? #1:', await p.evaluate(()=>document.getElementById('esoModal').style.display)); await p.click(`[onclick="esoDecide('nevela')"]`); await W(p,2500);
 console.log('server eso:', Q("select string_agg(id||':'||coalesce(eso_result,'-')||'/'||coalesce(slaughter,'-'),' ' order by id) from animals_pilot where id between 0 and 2"), '| hold:', Q("select coalesce(resolution,'OPEN')||':'||coalesce(note,'') from animal_holds where station='eso'"));
 await x.ctx.close();
 x=await open(b,'inner'); p=x.p; p.on('pageerror',e=>console.log('ERR',e.message));
 console.log('inner first:', await p.evaluate(()=>document.querySelector('#inGrid .num-cell.next')?.dataset.idx));
 await p.click('#scInner .gt-tbq'); await W(p,600); await p.click('#gtSheet button:has-text("סמן")'); await W(p,2500);
 console.log('inner after ?: cell2', await cls(p,2), '| next:', await p.evaluate(()=>document.querySelector('#inGrid .num-cell.next')?.dataset.idx));
 await p.click(cell(2)); await W(p,1000); console.log('inner opened #2 (rumen/maw/lung):', await p.evaluate(()=>[...document.querySelectorAll('.overlay.open,#rumenModal.open,#mawModal.open,#lungModal.open')].map(o=>o.id).join(',')));
 await b.close(); })();
